### PR TITLE
Showing a new link to the EQC QA tab and latest message

### PR DESCRIPTION
**Pull request by keul**
Take advantages of new qa_flag field

### CODE REVIEW

**Comment by keul** [comment]
Also: removed link to changelog, never released officially

**Comment by keul** [comment]
Also added a new `cads_message` key, which contains the latest live message for a dataset of warning or critical severity.

Example:

```json
  "cads:message": {
    "id": "contents/dummy-dataset/cems-test-warning.md",
    "summary": null,
    "url": null,
    "severity": "warning",
    "content": "This is a CAMS dataset!",
    "live": true
  }
```

This very same test message has been added to the `cems-fire-historical-v1` dataset

**Review by cettina-tosto — COMMENTED** [review]
@keul there are just some fixes to do on type-check or unit-tests, right?

**Comment by keul** [comment]
@cettina-tosto yep thanks, types fixed. About tests: something weird on the CI, locally it works

**Review by cettina-tosto — APPROVED** [review]

**Pull request merged**
